SecRuleEngine On
SecRequestBodyAccess On

# Load OWASP Core Rule Set (CRS).
Include /etc/nginx/modsecurity/crs-setup.conf
Include /usr/share/modsecurity-crs/rules/*.conf

# Add request correlation in audit logs when enabled.
SecAuditEngine RelevantOnly
SecAuditLog /tmp/modsecurity_audit.log
SecAuditLogParts ABIJDEFHZ
